language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

jobs:
  include:
    - stage: build
      script: ./scripts/travisci/build.sh
    - stage: test
      script: ./scripts/travisci/test.sh
    - stage: monorepo-split
      script: ./scripts/travisci/monorepo-split.sh
    - stage: deploy
      script: ./scripts/travisci/deploy.sh
