language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

jobs:
  include:
#    - stage: compile
#      script: ./scripts/travisci/compile.sh
#
#    - stage: test
#      script: ./scripts/travisci/test.sh

    - stage: build-and-push-images
#      if: (branch = master) AND (type = push)
      script: ./scripts/travisci/build-app-images.sh

    - stage: monorepo-split
      if: (branch = master) AND (type = push)
      before_script:
        # Encrypted SSH Deploy key: https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md
        - openssl aes-256-cbc -K $encrypted_a4fee1ae537a_key -iv $encrypted_a4fee1ae537a_iv -in udagram_rsa.enc -out ~/.ssh/udagram_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ~/.ssh/udagram_rsa
        - ssh-add ~/.ssh/udagram_rsa
        - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
      script: ./scripts/travisci/monorepo-split.sh

    - stage: deploy
      if: (branch = master) AND (type = push)
      script: ./scripts/travisci/deploy.sh
